source 'https://rubygems.org'

ruby '3.3.5'

gem 'activerecord', '~> 8.1'
gem 'faker'
gem 'fiddle'
gem 'logger', '~> 1.6'
gem 'ostruct'
gem 'pry'
gem 'rake'
gem 'rest-client'
gem 'rspec'
gem 'rubocop'
gem 'sqlite3', '~> 2.8.1'
